- name: Query Cluster Credentials
  ansible.builtin.uri:
    headers:
      Authorization: "Bearer {{ access_token.json.access_token }}"
    method: GET
    status_code: 200
    url: "{{ api_clusters_url + cluster_id }}/credentials"
  register: api_query_credentials_results

- name: Write Credentials to Artifact Directory
  vars:
    _console_password: "{{ api_query_credentials_results.json.password }}"
    _console_url: "{{ api_query_credentials_results.json.console_url }}"
    _console_username: "{{ api_query_credentials_results.json.username }}"
  ansible.builtin.copy:
    content: "{{ lookup('ansible.builtin.template', 'templates/credentials.j2') }}"
    dest: "{{ artifact_directory }}/credentials"
    mode: "0600"

- name: Query kubeconfig URL
  ansible.builtin.uri:
    headers:
      Authorization: "Bearer {{ access_token.json.access_token }}"
    method: GET
    status_code: 200
    url: "{{ api_clusters_url + cluster_id }}/downloads/credentials-presigned?file_name=kubeconfig"
  register: api_query_kubeconfig_url_results

- name: Download kubeconfig
  ansible.builtin.get_url:
    dest: "{{ artifact_directory }}/kubeconfig"
    url: "{{ api_query_kubeconfig_url_results.json.url }}"
    mode: "0600"
